.PHONY: clean realclean Converter MCSL SNTs pugixml clean_stats GRAPH_GEN

all: pugixml Converter MCSL GRAPH_GEN SNTs

SNTs: 
	@-mkdir -p build 2>&1
	cd build &&	cmake ../src && make && echo "SNTS_PATH=$$(pwd)" >> ../scripts/paths.sh

Converter:
	cd Converter/src/converter && make

pugixml:
	@-mkdir -p lib 2>&1
	cd lib && svn checkout http://pugixml.googlecode.com/svn/tags/release-1.2 pugixml
	@-mkdir -p lib/pugixml/build 2>&1
	cd lib/pugixml/build && cmake ../scripts && make && echo "PUGI_PATH=$$(pwd)" >> ../../../scripts/paths.sh

MCSL:
	cd MCSL && make

GRAPH_GEN:
	cd Graph_generator && make

#	DEGEN is not compiling at the moment
#DEGEN:
#	cd Degenerated && make

help:

	@echo "================================================================================"
	@echo "== This is the help function"
	@echo "== of the SNTs main Makefile."
	@echo "== Targets:"
	@echo "==     all       : Builds third-party library, the scheduler and the schedule"
	@echo "==                 \tconverter."
	@echo "=="
	@echo "==     SNTs      : Builds the C++ source files of the scheduler"
	@echo "=="
	@echo "==     MCSL      : Builds the C++ source files of the MCSL converter"
	@echo "=="
	@echo "==     DEGEN     : Builds the C++ source files of the Degenerated"
	@echo "=="                  NOT COMPILING!!!!!
	@echo "=="
	@echo "==     Converter : Builds the Java files for the schedule converter."
	@echo "=="
	@echo "==     pugixml   : Updates and builds the third party xml library."
	@echo "=="
	@echo "==     clean     : Cleans the build directories."
	@echo "=="
	@echo "==     clean_stats : Cleans the stats generated by the scheduler."
	@echo "=="
	@echo "==     realclean : Cleans the build directories and library directory."
	@echo "=="
	@echo "================================================================================"


clean:
	cd Converter/src/converter && make clean
	cd MCSL && make clean
	cd Graph_generator && make clean
	-rm -rf build
	-rm ./scripts/paths.sh

clean_stats:
	-rm stat-*

realclean: clean
	-rm -rf lib
